apiVersion: v1
kind: Namespace
metadata:
  name: kube-sentinel
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configfile
  namespace: kube-sentinel
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 10Mi