apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user:dashboard:view
  labels:
    app.kubernetes.io/controller: assign-team
rules:
- apiGroups: ["", "storage.k8s.io"]
  resources: ["persistentvolumes", "storageclasses"]
  verbs: ["get", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user:namespaces:view
  labels:
    app.kubernetes.io/controller: assign-team
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]