apiVersion: v1
kind: Namespace
metadata:
  name: gwp-promotion
  labels:
    app.kubernetes.io/controller: assign-team
    team: slick-checkout
    slick-checkout: ''
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: team-slick-checkout
#   namespace: gwp-promotion
#   labels:
#     app.kubernetes.io/controller: assign-team
#     team: slick-checkout
#     slick-checkout: ''
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: team-gwp-promotion-dashboard
#   namespace: gwp-promotion
#   labels:
#     app.kubernetes.io/controller: assign-team
#     team: slick-checkout
#     slick-checkout: ''
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: team:gwp-promotion:admin
  namespace: gwp-promotion
  labels:
    app.kubernetes.io/controller: assign-team
    team: slick-checkout
    slick-checkout: ''
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: team:gwp-promotion:admin
  namespace: gwp-promotion
  labels:
    app.kubernetes.io/controller: assign-team
    team: slick-checkout
    slick-checkout: ''
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: team:gwp-promotion:admin
subjects:
- kind: Group
  name: ea696194-d9bb-411d-8349-9a29c9ea5704
- kind: ServiceAccount
  name: team-slick-checkout-dashboard
  namespace: slick-checkout
- kind: ServiceAccount
  name: team-slick-checkout
  namespace: slick-checkout
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: team:gwp-promotion:admin
#   labels:
#     app.kubernetes.io/controller: assign-team
#     team: slick-checkout
#     slick-checkout: ''
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: user:dashboard:view
# subjects:
# - kind: Group
#   name: ea696194-d9bb-411d-8349-9a29c9ea5704
# - kind: ServiceAccount
#   name: team-gwp-promotion-dashboard
#   namespace: slick-checkout
# - kind: ServiceAccount
#   name: team-gwp-promotion
#   namespace: slick-checkout
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: team:gwp-promotion:ns
#   labels:
#     app.kubernetes.io/controller: assign-team
#     team: slick-checkout
#     slick-checkout: ''
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: user:namespaces:view
# subjects:
# - kind: Group
#   name: ea696194-d9bb-411d-8349-9a29c9ea5704
# - kind: ServiceAccount
#   name: team-gwp-promotion
#   namespace: slick-checkout
